{
 "title": "New dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Infra Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "200" }, "type": "raw_data" }
     ],
     "query": "log_source:\"redis\" OR log_source:\"sentinel\" OR log_source:\"syslog\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Systemd Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_source:syslog AND service_name:systemd",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Redis And Sentinel Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "log_source:(redis OR sentinel)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Backup Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "log_source:backup",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}