- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart elasticsearch nodes
  systemd:
    name: "elasticsearch@{{ item.name }}"
    state: restarted
  loop: "{{ elasticsearch_nodes }}"