name: Deploy app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          uname -a
          whoami
          pwd
          ls -la

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Show ansible version
        run: |
          ansible --version
          ansible-playbook --version

      - name: Run deploy app playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/playbooks/deploy_app.yml

      - name: Run migration playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/playbooks/migration.yml

      - name: Run restart app playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/playbooks/restart_app.yml
