apiVersion: v1
kind: Secret
metadata:
  name: uptime-monitor-secrets
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://CHANGE_ME:CHANGE_ME@10.211.55.3:5432/uptime_monitor"
  REDIS_SENTINEL_HOSTS: "10.211.55.3:26379,10.211.55.3:26380,10.211.55.3:26381"
  REDIS_PASSWORD: ""
